### ISSUE TITLE
socket.set_option(azmq::socket::subscribe("")); fails

### ISSUE THREAD

**Issue by toresbe** [zeromq/azmq#58]
When attempting this line (as used in the README.md example), I get a compiler error:

    3>..\common\zmq.cpp(28): error C2440: '<function-style-cast>' : cannot convert from 'const char [1]' to 'azmq::socket::subscribe'
    3>          No constructor could take the source type, or constructor overload resolution was ambiguous
    3>..\common\zmq.cpp(28): error C2780: 'boost::system::error_code azmq::socket::set_option(const Option &,boost::system::error_code &)' : expects 2 arguments - 1 provided
    3>          C:\libs\azmq\azmq/socket.hpp(245) : see declaration of 'azmq::socket::set_option'

I tried my best to read the code that fails but it's too advanced for someone just starting out in C++, so I simply wanted to make sure you knew of the error and feel free to contact me if any more information or any more tests are desired.

If I invoke it as azmq::socket::subscribe("", 1), it will fail with:

    detail/socket_service.hpp(269): error C2039: 'value_' : is not a member of 'azmq::opt::binary<6>'

However, if I add a void * value_ to the binary template, the code will run. 

Build environment: Win 8.1, VS2013 x64, latest snapshot.

**Comment by rodgert** [comment]
I changed the option implementation details since I last updated the
readme, I will look at it today.

**Comment by rodgert** [comment]
The issue is that arguments to the underlying zmq_setsockopt() for
subscribe/unsubscribe specify the type as 'binary data'. Currently the
opt::binary ctor takes void* data and size_t len, so you can't implicitly
construct it from a string literal.

I will make a patch to provide implicit conversion from char const* and
std::string on opt::binary. As a workaround you should be able to do -

auto subj = std::string("NASDAQ");
socket.set_option(azmq::socket::subscribe(subj.data(), subj.size()));

**Comment by rodgert** [comment]
Should teach me not to read these things on my phone ... I will patch both issues.

**Comment by toresbe** [comment]
Sweet! Thanks so much for the rapid response!

**Comment by rodgert** [comment]
Thanks, no problem. Please, if you find anything else, let me know.
